CREATE DATABASE pizzatech;

CREATE TABLE IF NOT EXISTS public.tb_tipo_produto(
	id UUID NOT NULL PRIMARY KEY,
	tipo VARCHAR(100) NOT NULL,
	CONSTRAINT chk_tipo CHECK (tipo IN ('PIZZA', 'HAMBURGER', 'REFRIGERANTE', 'AGUA', 'SUCO'))
);

CREATE TABLE IF NOT EXISTS public.tb_produto(
	id UUID NOT NULL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	quantidade INTEGER NOT NULL,
	preco NUMERIC(10,2) NOT NULL,
	id_tipo UUID NOT NULL REFERENCES tb_tipo_produto(id)
);